import os
from dotenv import load_dotenv

load_dotenv()

BOT_TOKEN = os.getenv("BOT_TOKEN", "8459834492:AAF-RW2qSaMA5QnKcgiMwtq9Zx-VwITSe7Y")
OWNER_ID = int(os.getenv("OWNER_ID", "8896123901"))
OTP_GROUP_ID = os.getenv("OTP_GROUP_ID", "-5305096346")

DEFAULT_SUPPORT_USERNAME = os.getenv("SUPPORT_USERNAME", "@Rabby1356")
DEFAULT_REFERRAL_AMOUNT = float(os.getenv("REFERRAL_AMOUNT", "0.005"))
DEFAULT_MIN_WITHDRAW = float(os.getenv("MIN_WITHDRAW", "0.5"))
DEFAULT_OTP_GROUP_LINK = os.getenv("OTP_GROUP_LINK", "https://t.me/your_otp_group")

DB_PATH = "bot_database.db"

SERVICE_EMOJIS = {
    "WHATSAPP": "📱",
    "FACEBOOK": "📘",
    "INSTAGRAM": "📸",
    "TELEGRAM": "✈️",
    "TWITTER": "🐦",
    "TIKTOK": "🎵",
    "SNAPCHAT": "👻",
    "GOOGLE": "🔍",
    "UBER": "🚗",
    "DISCORD": "🎮",
    "LINKEDIN": "💼",
    "NETFLIX": "🎬",
    "AMAZON": "📦",
    "PAYPAL": "💳",
    "MICROSOFT": "🪟",
    "APPLE": "🍎",
    "BINANCE": "💰",
    "OTHER": "💥",
}

COUNTRY_CODES = {
    "1876": {"name": "Jamaica",           "flag": "🇯🇲"},
    "1868": {"name": "Trinidad & Tobago", "flag": "🇹🇹"},
    "1849": {"name": "Dominican Rep",     "flag": "🇩🇴"},
    "1829": {"name": "Dominican Rep",     "flag": "🇩🇴"},
    "1809": {"name": "Dominican Rep",     "flag": "🇩🇴"},
    "1784": {"name": "St Vincent",        "flag": "🇻🇨"},
    "1767": {"name": "Dominica",          "flag": "🇩🇲"},
    "1758": {"name": "St Lucia",          "flag": "🇱🇨"},
    "1721": {"name": "Sint Maarten",      "flag": "🇸🇽"},
    "1684": {"name": "American Samoa",    "flag": "🇦🇸"},
    "1671": {"name": "Guam",              "flag": "🇬🇺"},
    "1670": {"name": "N. Mariana Is.",    "flag": "🇲🇵"},
    "1664": {"name": "Montserrat",        "flag": "🇲🇸"},
    "1649": {"name": "Turks & Caicos",    "flag": "🇹🇨"},
    "1473": {"name": "Grenada",           "flag": "🇬🇩"},
    "1441": {"name": "Bermuda",           "flag": "🇧🇲"},
    "1345": {"name": "Cayman Islands",    "flag": "🇰🇾"},
    "1340": {"name": "US Virgin Islands", "flag": "🇻🇮"},
    "1284": {"name": "British VI",        "flag": "🇻🇬"},
    "1268": {"name": "Antigua & Barbuda", "flag": "🇦🇬"},
    "1264": {"name": "Anguilla",          "flag": "🇦🇮"},
    "1246": {"name": "Barbados",          "flag": "🇧🇧"},
    "1242": {"name": "Bahamas",           "flag": "🇧🇸"},
    "998":  {"name": "Uzbekistan",        "flag": "🇺🇿"},
    "996":  {"name": "Kyrgyzstan",        "flag": "🇰🇬"},
    "995":  {"name": "Georgia",           "flag": "🇬🇪"},
    "994":  {"name": "Azerbaijan",        "flag": "🇦🇿"},
    "993":  {"name": "Turkmenistan",      "flag": "🇹🇲"},
    "992":  {"name": "Tajikistan",        "flag": "🇹🇯"},
    "977":  {"name": "Nepal",             "flag": "🇳🇵"},
    "976":  {"name": "Mongolia",          "flag": "🇲🇳"},
    "975":  {"name": "Bhutan",            "flag": "🇧🇹"},
    "974":  {"name": "Qatar",             "flag": "🇶🇦"},
    "973":  {"name": "Bahrain",           "flag": "🇧🇭"},
    "972":  {"name": "Israel",            "flag": "🇮🇱"},
    "971":  {"name": "UAE",               "flag": "🇦🇪"},
    "970":  {"name": "Palestine",         "flag": "🇵🇸"},
    "968":  {"name": "Oman",              "flag": "🇴🇲"},
    "967":  {"name": "Yemen",             "flag": "🇾🇪"},
    "966":  {"name": "Saudi Arabia",      "flag": "🇸🇦"},
    "965":  {"name": "Kuwait",            "flag": "🇰🇼"},
    "964":  {"name": "Iraq",              "flag": "🇮🇶"},
    "963":  {"name": "Syria",             "flag": "🇸🇾"},
    "962":  {"name": "Jordan",            "flag": "🇯🇴"},
    "961":  {"name": "Lebanon",           "flag": "🇱🇧"},
    "960":  {"name": "Maldives",          "flag": "🇲🇻"},
    "886":  {"name": "Taiwan",            "flag": "🇹🇼"},
    "880":  {"name": "Bangladesh",        "flag": "🇧🇩"},
    "856":  {"name": "Laos",              "flag": "🇱🇦"},
    "855":  {"name": "Cambodia",          "flag": "🇰🇭"},
    "853":  {"name": "Macau",             "flag": "🇲🇴"},
    "852":  {"name": "Hong Kong",         "flag": "🇭🇰"},
    "850":  {"name": "North Korea",       "flag": "🇰🇵"},
    "692":  {"name": "Marshall Islands",  "flag": "🇲🇭"},
    "691":  {"name": "Micronesia",        "flag": "🇫🇲"},
    "689":  {"name": "French Polynesia",  "flag": "🇵🇫"},
    "688":  {"name": "Tuvalu",            "flag": "🇹🇻"},
    "687":  {"name": "New Caledonia",     "flag": "🇳🇨"},
    "686":  {"name": "Kiribati",          "flag": "🇰🇮"},
    "685":  {"name": "Samoa",             "flag": "🇼🇸"},
    "683":  {"name": "Niue",              "flag": "🇳🇺"},
    "682":  {"name": "Cook Islands",      "flag": "🇨🇰"},
    "681":  {"name": "Wallis & Futuna",   "flag": "🇼🇫"},
    "680":  {"name": "Palau",             "flag": "🇵🇼"},
    "679":  {"name": "Fiji",              "flag": "🇫🇯"},
    "678":  {"name": "Vanuatu",           "flag": "🇻🇺"},
    "677":  {"name": "Solomon Islands",   "flag": "🇸🇧"},
    "676":  {"name": "Tonga",             "flag": "🇹🇴"},
    "675":  {"name": "Papua New Guinea",  "flag": "🇵🇬"},
    "674":  {"name": "Nauru",             "flag": "🇳🇷"},
    "673":  {"name": "Brunei",            "flag": "🇧🇳"},
    "670":  {"name": "East Timor",        "flag": "🇹🇱"},
    "599":  {"name": "Curacao",           "flag": "🇨🇼"},
    "598":  {"name": "Uruguay",           "flag": "🇺🇾"},
    "597":  {"name": "Suriname",          "flag": "🇸🇷"},
    "596":  {"name": "Martinique",        "flag": "🇲🇶"},
    "595":  {"name": "Paraguay",          "flag": "🇵🇾"},
    "594":  {"name": "French Guiana",     "flag": "🇬🇫"},
    "593":  {"name": "Ecuador",           "flag": "🇪🇨"},
    "592":  {"name": "Guyana",            "flag": "🇬🇾"},
    "591":  {"name": "Bolivia",           "flag": "🇧🇴"},
    "590":  {"name": "Guadeloupe",        "flag": "🇬🇵"},
    "509":  {"name": "Haiti",             "flag": "🇭🇹"},
    "507":  {"name": "Panama",            "flag": "🇵🇦"},
    "506":  {"name": "Costa Rica",        "flag": "🇨🇷"},
    "505":  {"name": "Nicaragua",         "flag": "🇳🇮"},
    "504":  {"name": "Honduras",          "flag": "🇭🇳"},
    "503":  {"name": "El Salvador",       "flag": "🇸🇻"},
    "502":  {"name": "Guatemala",         "flag": "🇬🇹"},
    "501":  {"name": "Belize",            "flag": "🇧🇿"},
    "423":  {"name": "Liechtenstein",     "flag": "🇱🇮"},
    "421":  {"name": "Slovakia",          "flag": "🇸🇰"},
    "420":  {"name": "Czech Republic",    "flag": "🇨🇿"},
    "389":  {"name": "North Macedonia",   "flag": "🇲🇰"},
    "387":  {"name": "Bosnia",            "flag": "🇧🇦"},
    "386":  {"name": "Slovenia",          "flag": "🇸🇮"},
    "385":  {"name": "Croatia",           "flag": "🇭🇷"},
    "383":  {"name": "Kosovo",            "flag": "🇽🇰"},
    "382":  {"name": "Montenegro",        "flag": "🇲🇪"},
    "381":  {"name": "Serbia",            "flag": "🇷🇸"},
    "380":  {"name": "Ukraine",           "flag": "🇺🇦"},
    "378":  {"name": "San Marino",        "flag": "🇸🇲"},
    "377":  {"name": "Monaco",            "flag": "🇲🇨"},
    "376":  {"name": "Andorra",           "flag": "🇦🇩"},
    "375":  {"name": "Belarus",           "flag": "🇧🇾"},
    "374":  {"name": "Armenia",           "flag": "🇦🇲"},
    "373":  {"name": "Moldova",           "flag": "🇲🇩"},
    "372":  {"name": "Estonia",           "flag": "🇪🇪"},
    "371":  {"name": "Latvia",            "flag": "🇱🇻"},
    "370":  {"name": "Lithuania",         "flag": "🇱🇹"},
    "359":  {"name": "Bulgaria",          "flag": "🇧🇬"},
    "358":  {"name": "Finland",           "flag": "🇫🇮"},
    "357":  {"name": "Cyprus",            "flag": "🇨🇾"},
    "356":  {"name": "Malta",             "flag": "🇲🇹"},
    "355":  {"name": "Albania",           "flag": "🇦🇱"},
    "354":  {"name": "Iceland",           "flag": "🇮🇸"},
    "353":  {"name": "Ireland",           "flag": "🇮🇪"},
    "352":  {"name": "Luxembourg",        "flag": "🇱🇺"},
    "351":  {"name": "Portugal",          "flag": "🇵🇹"},
    "350":  {"name": "Gibraltar",         "flag": "🇬🇮"},
    "299":  {"name": "Greenland",         "flag": "🇬🇱"},
    "298":  {"name": "Faroe Islands",     "flag": "🇫🇴"},
    "297":  {"name": "Aruba",             "flag": "🇦🇼"},
    "291":  {"name": "Eritrea",           "flag": "🇪🇷"},
    "290":  {"name": "St Helena",         "flag": "🇸🇭"},
    "269":  {"name": "Comoros",           "flag": "🇰🇲"},
    "268":  {"name": "Eswatini",          "flag": "🇸🇿"},
    "267":  {"name": "Botswana",          "flag": "🇧🇼"},
    "266":  {"name": "Lesotho",           "flag": "🇱🇸"},
    "265":  {"name": "Malawi",            "flag": "🇲🇼"},
    "264":  {"name": "Namibia",           "flag": "🇳🇦"},
    "263":  {"name": "Zimbabwe",          "flag": "🇿🇼"},
    "262":  {"name": "Reunion",           "flag": "🇷🇪"},
    "261":  {"name": "Madagascar",        "flag": "🇲🇬"},
    "260":  {"name": "Zambia",            "flag": "🇿🇲"},
    "258":  {"name": "Mozambique",        "flag": "🇲🇿"},
    "257":  {"name": "Burundi",           "flag": "🇧🇮"},
    "256":  {"name": "Uganda",            "flag": "🇺🇬"},
    "255":  {"name": "Tanzania",          "flag": "🇹🇿"},
    "254":  {"name": "Kenya",             "flag": "🇰🇪"},
    "253":  {"name": "Djibouti",          "flag": "🇩🇯"},
    "252":  {"name": "Somalia",           "flag": "🇸🇴"},
    "251":  {"name": "Ethiopia",          "flag": "🇪🇹"},
    "250":  {"name": "Rwanda",            "flag": "🇷🇼"},
    "249":  {"name": "Sudan",             "flag": "🇸🇩"},
    "248":  {"name": "Seychelles",        "flag": "🇸🇨"},
    "245":  {"name": "Guinea-Bissau",     "flag": "🇬🇼"},
    "244":  {"name": "Angola",            "flag": "🇦🇴"},
    "243":  {"name": "Congo DR",          "flag": "🇨🇩"},
    "242":  {"name": "Congo",             "flag": "🇨🇬"},
    "241":  {"name": "Gabon",             "flag": "🇬🇦"},
    "240":  {"name": "Eq. Guinea",        "flag": "🇬🇶"},
    "239":  {"name": "Sao Tome",          "flag": "🇸🇹"},
    "238":  {"name": "Cape Verde",        "flag": "🇨🇻"},
    "237":  {"name": "Cameroon",          "flag": "🇨🇲"},
    "236":  {"name": "Central Africa",    "flag": "🇨🇫"},
    "235":  {"name": "Chad",              "flag": "🇹🇩"},
    "234":  {"name": "Nigeria",           "flag": "🇳🇬"},
    "233":  {"name": "Ghana",             "flag": "🇬🇭"},
    "232":  {"name": "Sierra Leone",      "flag": "🇸🇱"},
    "231":  {"name": "Liberia",           "flag": "🇱🇷"},
    "230":  {"name": "Mauritius",         "flag": "🇲🇺"},
    "229":  {"name": "Benin",             "flag": "🇧🇯"},
    "228":  {"name": "Togo",              "flag": "🇹🇬"},
    "227":  {"name": "Niger",             "flag": "🇳🇪"},
    "226":  {"name": "Burkina Faso",      "flag": "🇧🇫"},
    "225":  {"name": "Ivory Coast",       "flag": "🇨🇮"},
    "224":  {"name": "Guinea",            "flag": "🇬🇳"},
    "223":  {"name": "Mali",              "flag": "🇲🇱"},
    "222":  {"name": "Mauritania",        "flag": "🇲🇷"},
    "221":  {"name": "Senegal",           "flag": "🇸🇳"},
    "220":  {"name": "Gambia",            "flag": "🇬🇲"},
    "218":  {"name": "Libya",             "flag": "🇱🇾"},
    "216":  {"name": "Tunisia",           "flag": "🇹🇳"},
    "213":  {"name": "Algeria",           "flag": "🇩🇿"},
    "212":  {"name": "Morocco",           "flag": "🇲🇦"},
    "211":  {"name": "South Sudan",       "flag": "🇸🇸"},
    "98":   {"name": "Iran",              "flag": "🇮🇷"},
    "95":   {"name": "Myanmar",           "flag": "🇲🇲"},
    "94":   {"name": "Sri Lanka",         "flag": "🇱🇰"},
    "93":   {"name": "Afghanistan",       "flag": "🇦🇫"},
    "92":   {"name": "Pakistan",          "flag": "🇵🇰"},
    "91":   {"name": "India",             "flag": "🇮🇳"},
    "90":   {"name": "Turkey",            "flag": "🇹🇷"},
    "86":   {"name": "China",             "flag": "🇨🇳"},
    "84":   {"name": "Vietnam",           "flag": "🇻🇳"},
    "82":   {"name": "South Korea",       "flag": "🇰🇷"},
    "81":   {"name": "Japan",             "flag": "🇯🇵"},
    "77":   {"name": "Kazakhstan",        "flag": "🇰🇿"},
    "66":   {"name": "Thailand",          "flag": "🇹🇭"},
    "65":   {"name": "Singapore",         "flag": "🇸🇬"},
    "64":   {"name": "New Zealand",       "flag": "🇳🇿"},
    "63":   {"name": "Philippines",       "flag": "🇵🇭"},
    "62":   {"name": "Indonesia",         "flag": "🇮🇩"},
    "61":   {"name": "Australia",         "flag": "🇦🇺"},
    "60":   {"name": "Malaysia",          "flag": "🇲🇾"},
    "58":   {"name": "Venezuela",         "flag": "🇻🇪"},
    "57":   {"name": "Colombia",          "flag": "🇨🇴"},
    "56":   {"name": "Chile",             "flag": "🇨🇱"},
    "55":   {"name": "Brazil",            "flag": "🇧🇷"},
    "54":   {"name": "Argentina",         "flag": "🇦🇷"},
    "53":   {"name": "Cuba",              "flag": "🇨🇺"},
    "52":   {"name": "Mexico",            "flag": "🇲🇽"},
    "51":   {"name": "Peru",              "flag": "🇵🇪"},
    "49":   {"name": "Germany",           "flag": "🇩🇪"},
    "48":   {"name": "Poland",            "flag": "🇵🇱"},
    "47":   {"name": "Norway",            "flag": "🇳🇴"},
    "46":   {"name": "Sweden",            "flag": "🇸🇪"},
    "45":   {"name": "Denmark",           "flag": "🇩🇰"},
    "44":   {"name": "UK",                "flag": "🇬🇧"},
    "43":   {"name": "Austria",           "flag": "🇦🇹"},
    "41":   {"name": "Switzerland",       "flag": "🇨🇭"},
    "40":   {"name": "Romania",           "flag": "🇷🇴"},
    "39":   {"name": "Italy",             "flag": "🇮🇹"},
    "36":   {"name": "Hungary",           "flag": "🇭🇺"},
    "34":   {"name": "Spain",             "flag": "🇪🇸"},
    "33":   {"name": "France",            "flag": "🇫🇷"},
    "32":   {"name": "Belgium",           "flag": "🇧🇪"},
    "31":   {"name": "Netherlands",       "flag": "🇳🇱"},
    "30":   {"name": "Greece",            "flag": "🇬🇷"},
    "27":   {"name": "South Africa",      "flag": "🇿🇦"},
    "20":   {"name": "Egypt",             "flag": "🇪🇬"},
    "7":    {"name": "Russia",            "flag": "🇷🇺"},
    "1":    {"name": "USA/Canada",        "flag": "🇺🇸"},
}

# ============================================================
# COUNTRY NAME -> ISO ALPHA-2 SHORT CODE (for display, e.g. "Malaysia (MY)")
# ============================================================
COUNTRY_NAME_TO_ISO2 = {
    "Afghanistan": "AF", "Albania": "AL", "Algeria": "DZ", "American Samoa": "AS", "Andorra": "AD",
    "Angola": "AO", "Anguilla": "AI", "Antigua & Barbuda": "AG", "Argentina": "AR", "Armenia": "AM",
    "Aruba": "AW", "Australia": "AU", "Austria": "AT", "Azerbaijan": "AZ", "Bahamas": "BS",
    "Bahrain": "BH", "Bangladesh": "BD", "Barbados": "BB", "Belarus": "BY", "Belgium": "BE",
    "Belize": "BZ", "Benin": "BJ", "Bermuda": "BM", "Bhutan": "BT", "Bolivia": "BO", "Bosnia": "BA",
    "Botswana": "BW", "Brazil": "BR", "British VI": "VG", "Brunei": "BN", "Bulgaria": "BG",
    "Burkina Faso": "BF", "Burundi": "BI", "Cambodia": "KH", "Cameroon": "CM", "Cape Verde": "CV",
    "Cayman Islands": "KY", "Central Africa": "CF", "Chad": "TD", "Chile": "CL", "China": "CN",
    "Colombia": "CO", "Comoros": "KM", "Congo": "CG", "Congo DR": "CD", "Cook Islands": "CK",
    "Costa Rica": "CR", "Croatia": "HR", "Cuba": "CU", "Curacao": "CW", "Cyprus": "CY",
    "Czech Republic": "CZ", "Denmark": "DK", "Djibouti": "DJ", "Dominica": "DM", "Dominican Rep": "DO",
    "East Timor": "TL", "Ecuador": "EC", "Egypt": "EG", "El Salvador": "SV", "Eq. Guinea": "GQ",
    "Eritrea": "ER", "Estonia": "EE", "Eswatini": "SZ", "Ethiopia": "ET", "Faroe Islands": "FO",
    "Fiji": "FJ", "Finland": "FI", "France": "FR", "French Guiana": "GF", "French Polynesia": "PF",
    "Gabon": "GA", "Gambia": "GM", "Georgia": "GE", "Germany": "DE", "Ghana": "GH", "Gibraltar": "GI",
    "Greece": "GR", "Greenland": "GL", "Grenada": "GD", "Guadeloupe": "GP", "Guam": "GU",
    "Guatemala": "GT", "Guinea": "GN", "Guinea-Bissau": "GW", "Guyana": "GY", "Haiti": "HT",
    "Honduras": "HN", "Hong Kong": "HK", "Hungary": "HU", "Iceland": "IS", "India": "IN",
    "Indonesia": "ID", "Iran": "IR", "Iraq": "IQ", "Ireland": "IE", "Israel": "IL", "Italy": "IT",
    "Ivory Coast": "CI", "Jamaica": "JM", "Japan": "JP", "Jordan": "JO", "Kazakhstan": "KZ",
    "Kenya": "KE", "Kiribati": "KI", "Kosovo": "XK", "Kuwait": "KW", "Kyrgyzstan": "KG", "Laos": "LA",
    "Latvia": "LV", "Lebanon": "LB", "Lesotho": "LS", "Liberia": "LR", "Libya": "LY",
    "Liechtenstein": "LI", "Lithuania": "LT", "Luxembourg": "LU", "Macau": "MO", "Madagascar": "MG",
    "Malawi": "MW", "Malaysia": "MY", "Maldives": "MV", "Mali": "ML", "Malta": "MT",
    "Marshall Islands": "MH", "Martinique": "MQ", "Mauritania": "MR", "Mauritius": "MU",
    "Mexico": "MX", "Micronesia": "FM", "Moldova": "MD", "Monaco": "MC", "Mongolia": "MN",
    "Montenegro": "ME", "Montserrat": "MS", "Morocco": "MA", "Mozambique": "MZ", "Myanmar": "MM",
    "N. Mariana Is.": "MP", "Namibia": "NA", "Nauru": "NR", "Nepal": "NP", "Netherlands": "NL",
    "New Caledonia": "NC", "New Zealand": "NZ", "Nicaragua": "NI", "Niger": "NE", "Nigeria": "NG",
    "Niue": "NU", "North Korea": "KP", "North Macedonia": "MK", "Norway": "NO", "Oman": "OM",
    "Pakistan": "PK", "Palau": "PW", "Palestine": "PS", "Panama": "PA", "Papua New Guinea": "PG",
    "Paraguay": "PY", "Peru": "PE", "Philippines": "PH", "Poland": "PL", "Portugal": "PT",
    "Qatar": "QA", "Reunion": "RE", "Romania": "RO", "Russia": "RU", "Rwanda": "RW", "Samoa": "WS",
    "San Marino": "SM", "Sao Tome": "ST", "Saudi Arabia": "SA", "Senegal": "SN", "Serbia": "RS",
    "Seychelles": "SC", "Sierra Leone": "SL", "Singapore": "SG", "Sint Maarten": "SX",
    "Slovakia": "SK", "Slovenia": "SI", "Solomon Islands": "SB", "Somalia": "SO",
    "South Africa": "ZA", "South Korea": "KR", "South Sudan": "SS", "Spain": "ES", "Sri Lanka": "LK",
    "St Helena": "SH", "St Lucia": "LC", "St Vincent": "VC", "Sudan": "SD", "Suriname": "SR",
    "Sweden": "SE", "Switzerland": "CH", "Syria": "SY", "Taiwan": "TW", "Tajikistan": "TJ",
    "Tanzania": "TZ", "Thailand": "TH", "Togo": "TG", "Tonga": "TO", "Trinidad & Tobago": "TT",
    "Tunisia": "TN", "Turkey": "TR", "Turkmenistan": "TM", "Turks & Caicos": "TC", "Tuvalu": "TV",
    "UAE": "AE", "UK": "GB", "US Virgin Islands": "VI", "USA/Canada": "US", "Uganda": "UG",
    "Ukraine": "UA", "Uruguay": "UY", "Uzbekistan": "UZ", "Vanuatu": "VU", "Venezuela": "VE",
    "Vietnam": "VN", "Wallis & Futuna": "WF", "Yemen": "YE", "Zambia": "ZM", "Zimbabwe": "ZW",
}

def get_country_iso2(country_name: str) -> str:
    """Country name থেকে ISO alpha-2 short code রিটার্ন করে (না পেলে খালি স্ট্রিং)"""
    return COUNTRY_NAME_TO_ISO2.get(country_name, "")
